### ISSUE TITLE
Navbar is not responsive on mobile view

### ISSUE THREAD

**Issue by AnishTiwari16** [ankitrout2903/Swingyy#23]
<img width="401" alt="Screenshot 2023-10-04 at 12 34 40 AM" src="https://github.com/ankitrout2903/Swingyy/assets/87610940/8ba92da3-b32d-46c8-b364-ad5d36c525f0">

**Comment by AnishTiwari16** [comment]
i can pick it up, can u assign it to me

**Comment by GouravKumar13** [comment]
@AnishTiwari16  don't  be a fraud assign it to me
