### ISSUE TITLE
The whole flow is breaking the container is not taking proper width

### ISSUE THREAD

**Issue by GouravKumar13** [ankitrout2903/Swingyy#25]
![image](https://github.com/ankitrout2903/Swingyy/assets/55110247/5c69a999-54e0-4d02-9ce0-8fa6b42eb10c)

**Comment by GouravKumar13** [comment]
can you assign this to me

**Comment by AnishTiwari16** [comment]
@ankitrout2903 please check the width is not wrt screen

**Comment by GouravKumar13** [comment]
I have changed the UI not its not braking
