### ISSUE TITLE
Login card is not properly styled in mobile view, missing padding and center alignment

### ISSUE THREAD

**Issue by AnishTiwari16** [ankitrout2903/Swingyy#27]
<img width="365" alt="Screenshot 2023-10-04 at 1 41 02 AM" src="https://github.com/ankitrout2903/Swingyy/assets/87610940/aeb5c147-b39e-4537-80d9-870f8bc44230">

**Comment by AnishTiwari16** [comment]
will fix it, please assign

**Comment by GouravKumar13** [comment]
@AnishTiwari16  @ankitrout2903  i have made changes it will be fixed after you merge my PR
