### ISSUE TITLE
New Login Page

### ISSUE THREAD

**Issue by Villain45** [ankitrout2903/Swingyy#3]
Will be changing the UI of the login page

**Comment by ankitrout2903** [comment]
Yess go ahead 😊😊

**Comment by ankitrout2903** [comment]
> Will be changing the UI of the login page

yes You can go ahead 🫠 also make sure you give PR after oct 1st so that you get a valid PR.

**Comment by AnshulGoyal589** [comment]
i want to contribute in this under hactoberfest 2023, kindly assign this issue to me.
