### ISSUE TITLE
login card taking wide width needs to different from mobile

### ISSUE THREAD

**Issue by AnishTiwari16** [ankitrout2903/Swingyy#30]
<img width="1422" alt="Screenshot 2023-10-04 at 2 01 39 AM" src="https://github.com/ankitrout2903/Swingyy/assets/87610940/b8e93604-3fe0-4eef-9ffb-9ec5d3f38f1a">

**Comment by AnishTiwari16** [comment]
please assign will add media query

**Comment by GouravKumar13** [comment]
can you assign it to me
@AnishTiwari16

**Comment by AnishTiwari16** [comment]
already raised a PR -> https://github.com/ankitrout2903/Swingyy/pull/31
