### ISSUE TITLE
Unused APIs

### ISSUE THREAD

**Issue by V-nsh** [ankitrout2903/Swingyy#4]
well I went through the code and saw a couple of issues, you've created APIs for login and registration but not using it ig? You are trying to show everyone on the DB except the user himself on the friends list, but I don't see you storing these registered people? Also I don't see any option to add friends too.

**Comment by ankitrout2903** [comment]
> well I went through the code and saw a couple of issues, you've created APIs for login and registration but not using it ig? You are trying to show everyone on the DB except the user himself on the friends list, but I don't see you storing these registered people? Also I don't see any option to add friends too.

Yess great observation go ahead and give a contribution. 🤠🤠

**Comment by V-nsh** [comment]
man whoever made the recent push, please ignore the node_modules. it has completely messed up my git , I wanted to make a PR  but now I have to fix this..
![image](https://github.com/ankitrout2903/Swingyy/assets/68783139/f3722de0-93de-48a4-8c07-e4fa53a391f4)
