### ISSUE TITLE
Want to add CODE_OF_CONDUCT.md and LICENSE to your repo 

### ISSUE THREAD

**Issue by sb-decoder** [ankitrout2903/Swingyy#5]
Assign me this task under hacktoberfest @ankitrout2903

**Comment by sb-decoder** [comment]
hey plz add the necessary labels

**Comment by sb-decoder** [comment]
@ankitrout2903 Thanks for merge. Can you please add the hacktoberfest-accepted label to the merged PR

**Comment by ankitrout2903** [comment]
okay bro can you tell me how to do this as i am not to hacktoberfest

**Comment by sb-decoder** [comment]
just like you add the documentation label, in the same way add hacktoberfest-accepted or hacktoberfest  label

**Comment by ankitrout2903** [comment]
is this okay

**Comment by sb-decoder** [comment]
yeah, Thanks
